name: ReBOOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: make gcc mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-SDL2_mixer mingw64/mingw-w64-x86_64-SDL2_image mingw64/mingw-w64-x86_64-SDL2_net
    - run: make reboom MINGW=1
    - run: file ./build/reboom.exe

    - name: Create Binary Package
      shell: bash
      run: |
        cd build
        mkdir binary_package_msys2
        cp C:/msys64/usr/bin/msys-2.0.dll binary_package_msys2
        cp reboom.exe binary_package_msys2
    - name: Upload Binary Package
      uses: actions/upload-artifact@v1
      with:
        path: build/binary_package_msys2
        name: binary_package_msys2
